"""empty message

Revision ID: 078dadcce1cf
Revises: f93d55fbd223
Create Date: 2024-11-10 17:22:06.372229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '078dadcce1cf'
down_revision = 'f93d55fbd223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sex', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('job', sa.String(length=100), nullable=False))
        batch_op.drop_column('gender')
        batch_op.drop_column('job_category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_category', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=10), nullable=False))
        batch_op.drop_column('job')
        batch_op.drop_column('sex')

    # ### end Alembic commands ###
