"""empty message

Revision ID: 465c0bb7a571
Revises: 5a8b107d99b4
Create Date: 2024-12-02 15:50:56.553400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465c0bb7a571'
down_revision = '5a8b107d99b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('k_economy', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('k_welfare', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('k_diplomacy', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('k_environmnet', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('k_politics', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('k_technology', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('k_human', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('k_defense', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('k_law', sa.Integer(), nullable=True))
        batch_op.drop_column('keyword2')
        batch_op.drop_column('keyword1')
        batch_op.drop_column('keyword3')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keyword3', sa.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('keyword1', sa.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('keyword2', sa.VARCHAR(length=150), nullable=True))
        batch_op.drop_column('k_law')
        batch_op.drop_column('k_defense')
        batch_op.drop_column('k_human')
        batch_op.drop_column('k_technology')
        batch_op.drop_column('k_politics')
        batch_op.drop_column('k_environmnet')
        batch_op.drop_column('k_diplomacy')
        batch_op.drop_column('k_welfare')
        batch_op.drop_column('k_economy')

    # ### end Alembic commands ###
