"""empty message

Revision ID: 5a8b107d99b4
Revises: 5396f23bc379
Create Date: 2024-11-24 20:51:20.405999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a8b107d99b4'
down_revision = '5396f23bc379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keyword1', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('keyword2', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('keyword3', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('keyword3')
        batch_op.drop_column('keyword2')
        batch_op.drop_column('keyword1')

    # ### end Alembic commands ###
