"""empty message

Revision ID: 8f892418c3af
Revises: c863b91e1f43
Create Date: 2024-12-02 16:46:30.237422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f892418c3af'
down_revision = 'c863b91e1f43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legislation', sa.Boolean(), nullable=True))
        batch_op.drop_column('law')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('law', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('legislation')

    # ### end Alembic commands ###
