"""empty message

Revision ID: b01602fd58fe
Revises: 81efe013c030
Create Date: 2024-12-05 18:03:08.712654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b01602fd58fe'
down_revision = '81efe013c030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.alter_column('economy',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('welfare',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('security',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('environment',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('political_reform',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('technology',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('human_rights',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('defense',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('legislation',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('total',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=150),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.String(length=150),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('legislation',
               existing_type=sa.String(length=150),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('defense',
               existing_type=sa.String(length=150),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('human_rights',
               existing_type=sa.String(length=150),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('technology',
               existing_type=sa.String(length=150),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('political_reform',
               existing_type=sa.String(length=150),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('environment',
               existing_type=sa.String(length=150),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('security',
               existing_type=sa.String(length=150),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('welfare',
               existing_type=sa.String(length=150),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('economy',
               existing_type=sa.String(length=150),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
