"""empty message

Revision ID: c863b91e1f43
Revises: 465c0bb7a571
Create Date: 2024-12-02 16:02:51.260671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c863b91e1f43'
down_revision = '465c0bb7a571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('economy', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('welfare', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('security', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('environment', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('political_reform', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('technology', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('human_rights', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('defense', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('law', sa.Boolean(), nullable=True))
        batch_op.drop_column('k_law')
        batch_op.drop_column('k_human')
        batch_op.drop_column('k_environmnet')
        batch_op.drop_column('k_defense')
        batch_op.drop_column('k_politics')
        batch_op.drop_column('k_diplomacy')
        batch_op.drop_column('k_technology')
        batch_op.drop_column('k_economy')
        batch_op.drop_column('k_welfare')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('k_welfare', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('k_economy', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('k_technology', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('k_diplomacy', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('k_politics', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('k_defense', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('k_environmnet', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('k_human', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('k_law', sa.INTEGER(), nullable=True))
        batch_op.drop_column('law')
        batch_op.drop_column('defense')
        batch_op.drop_column('human_rights')
        batch_op.drop_column('technology')
        batch_op.drop_column('political_reform')
        batch_op.drop_column('environment')
        batch_op.drop_column('security')
        batch_op.drop_column('welfare')
        batch_op.drop_column('economy')

    # ### end Alembic commands ###
